#!/usr/bin/env node

/* 
This line runs this file which generates Script/examManifest.js
node tools/generateExamManifest.js; 


git add Script/examManifest.js; 
git commit -m "chore: regenerate examManifest.js"
*/
const fs = require("fs").promises;
const path = require("path");

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const res = path.resolve(dir, entry.name);
      return entry.isDirectory() ? walk(res) : res;
    })
  );
  return Array.prototype.concat(...files);
}

function titleCase(name) {
  return name.replace(/[-_]/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
}

async function generate() {
  const repoRoot = path.resolve(__dirname, "..");
  const examsDir = path.join(repoRoot, "Exams");
  const scriptDir = path.join(repoRoot, "Script");

  const allFiles = await walk(examsDir);
  const jsFiles = allFiles.filter((f) => f.endsWith(".js"));

  const exams = jsFiles.map((fullPath) => {
    const relFromExams = path.relative(examsDir, fullPath); // e.g. HTML/html_basics.js
    const parts = relFromExams.split(path.sep);
    const fileName = parts.pop();
    const category = parts.length ? parts.join("/") : "General";
    const id = fileName.replace(/\.js$/, "");
    const title = titleCase(id);
    // path relative to Script folder, use posix style for browser imports
    let relPath = path.relative(scriptDir, fullPath).split(path.sep).join("/");
    if (!relPath.startsWith(".")) relPath = "./" + relPath;
    return { id, category, title, path: relPath };
  });

  // Sort by category then id
  exams.sort((a, b) => (a.category + a.id).localeCompare(b.category + b.id));

  const outFile = path.join(scriptDir, "examManifest.js");
  const header = `// Auto-generated by tools/generateExamManifest.js - do not edit by hand\n// Run: node tools/generateExamManifest.js\n\n`;
  const body =
    "export const examList = " + JSON.stringify(exams, null, 2) + ";\n";

  await fs.writeFile(outFile, header + body, "utf8");
  console.log("Wrote", outFile);
}

generate().catch((err) => {
  console.error(err);
  process.exit(1);
});
